const path = require("path");
const Koa = require("koa");
const cors = require("koa2-cors");
const bodyParser = require("koa-bodyparser");
const router = require("./route");
const authSlat = require("./utils/auth");
const app = new Koa();
app.use(cors());
app.use(bodyParser());
app.use(authSlat);
app.use(router.routes()).use(router.allowedMethods());
const port = process.env.PORT || 9999;
app.listen(port);
console.log("http://127.0.0.1:" + port);
